name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # يوميًا منتصف الليل
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update GitHub Stats
        run: echo "Workflow triggered to update README & Stats"
